### ISSUE TITLE
Display twitter feed in side panel

### ISSUE THREAD

**Issue by Brian393** [Brian393/ecotopia-today#10]
@edwardsharp

I would like to display a twitter feed in the html text panel of WatershedHanford. It should go in an accordion with the title Hanford Challenge twitter feed, and it should look just like the ones in WatershedTerminals, except the user will access it by clicking on an accordion panel.

The address of the feed is:

https://twitter.com/HanfordC

The official TwitterPublish code is: 

<a class="twitter-timeline" data-width="340" data-height="500" href="https://twitter.com/HanfordC?ref_src=twsrc%5Etfw">Tweets by HanfordC</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by edwardsharp** [comment]
so, you can just use the `twttr` widget like so (note: `this.$refs` refers to html elements that have an attribute `ref` e.g. `<div ref="whatever">` ): 

```js
window.twttr.widgets.createTimeline(
  {
    sourceType: 'url',
    url: 'https://twitter.com/HanfordC'
  },
  this.$refs.twttrHanfordC
)
```

so you can add a `mounted` function definition to `src/views/watershed/WatershedHanford.vue` that includes the above `twttr.widgets.createTimeline` function. 

```js
mounted: function () {
  ...
}
```
then you can just add an empty div with a `ref` attribute inside an `<Accordion>` that `twttr.widgets.createTimeline()` will use to display the tweets, like so:
```html
<Accordion :open="false">
    <div ref="twttrHanfordC"></div>
</Accordion>
```
