### ISSUE TITLE
Minify error

### ISSUE THREAD

**Issue by Brian393** [Brian393/ecotopia-today#5]
@edwardsharp

Hello ed -

I have another problem with the minify script on deployment. See the end of the terminal commands below. As usual, I am uncertain whether this problem has to do with the way I am using git, or some error in the .vue files.

I want to give you a complete sequence of what has happened:

I am on my traveling computer.

After receiving your last observations and acting on them, I made another commit on Bioregion-1. Simple things, mainly having to do with the text in Megaregion/Vanport. Everything worked perfect when I ran "npm start." I fixed the lint errors and felt ready to publish the new work. In fact I had delayed this publication, which should have been done a week ago. So I did not want to wait anymore.

I switched to master. Git status said I was behind two commits with regard to origin-master. I did not know what to do, because there had been some confusing merge conflicts when I briefly switched back to my home computer after my Portland trip. I thought those two commits on origin-master were probably mistaken and useless. So I decided to ignore them. With the local master checked out I ran "git merge Bioregion-1." Then I ran "git push origin." After that I ran "npm run deploy." And I got the minify problem that you can see at the end of the sequence of terminal commands below.

It is possible that this problem has nothing to do with the two commits on origin-master. I stress that Bioregion-1 works perfectly when I run npm start.

It's also possible that I could solve the problem by reverting my merge on both the local master and origin-master, and then pulling those two commits from origin-master. However there are various ways to revert the merge and the subsequent push, and I am not sure which one I should use, or whether that's even the problem. 

IMPORTANT:

In the interests of learning git, it would be great to know how I should revert a merge or a push. 

It would also be great to know how I should change from one computer to the other, in order to avoid any future problems. Assuming origin-master is up to date with commits made on the traveling computer, then what do I do when I come back to the home computer? 

Finally I should add that I did not yet act on your suggestion that I "prettify" my geojson files using Atom, because I could not figure out how to do that or even what it means. I doubt that's the problem, but who knows.

thanks in advance for your assistance,

Brian

TERMINAL COMMANDS AND RESULTS

^Cbrian@nemozine:~/Git/ecotopia-today$ git status
On branch Bioregion-1
Your branch is ahead of 'origin/Bioregion-1' by 1 commit.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean
brian@nemozine:~/Git/ecotopia-today$ git push
warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

Username for 'https://github.com': Brian393
Password for 'https://Brian393@github.com': 
Counting objects: 19, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (19/19), done.
Writing objects: 100% (19/19), 83.31 KiB | 0 bytes/s, done.
Total 19 (delta 12), reused 0 (delta 0)
remote: Resolving deltas: 100% (12/12), completed with 12 local objects.
To https://github.com/Brian393/ecotopia-today.git
   0a925d1..265f468  Bioregion-1 -> Bioregion-1

brian@nemozine:~/Git/ecotopia-today$ git checkout master
Switched to branch 'master'
Your branch is behind 'origin/master' by 2 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

brian@nemozine:~/Git/ecotopia-today$ git merge Bioregion-1
Updating 928ce55..265f468
Fast-forward
 public/geojson/ColumbiaGeneratingStation.jpg   | Bin 0 -> 365615 bytes
 public/geojson/VanUnderlayer.geojson           |   8 ++
 public/icons/legends/building.png              | Bin 0 -> 5540 bytes
 public/icons/legends/vanportwater.png          | Bin 0 -> 4457 bytes
 public/icons/legends/vanstreets.png            | Bin 0 -> 1788 bytes
 public/images/VanportUnderwater.jpg            | Bin 0 -> 71233 bytes
 src/components/AppNav.vue                      |   4 +
 src/components/MapMegaregion.vue               |  67 ++++++++++++++-
 src/components/MapWatershed.vue                |   9 ++
 src/router.js                                  |   8 ++
 src/views/megaregion/MegaregionVanport.vue     | 109 +++++++++++++++++++++++++
 src/views/watershed/WatershedHanfordPlumes.vue |   4 +-
 src/views/watershed/WatershedIntroduction.vue  |  22 -----
 src/views/watershed/WatershedTerminals.vue     |   2 +-
 14 files changed, 204 insertions(+), 29 deletions(-)
 create mode 100644 public/geojson/ColumbiaGeneratingStation.jpg
 create mode 100644 public/geojson/VanUnderlayer.geojson
 create mode 100644 public/icons/legends/building.png
 create mode 100644 public/icons/legends/vanportwater.png
 create mode 100644 public/icons/legends/vanstreets.png
 create mode 100644 public/images/VanportUnderwater.jpg
 create mode 100644 src/views/megaregion/MegaregionVanport.vue

brian@nemozine:~/Git/ecotopia-today$ git push origin
warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

Username for 'https://github.com': Brian393
Password for 'https://Brian393@github.com': 
Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/Brian393/ecotopia-today.git
   3fd2d27..265f468  master -> master

brian@nemozine:~/Git/ecotopia-today$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

brian@nemozine:~/Git/ecotopia-today$ npm run deploy

> ecotopia-today@0.0.1 predeploy /home/brian/Git/ecotopia-today
> npm run build

> ecotopia-today@0.0.1 build /home/brian/Git/ecotopia-today
> vue-cli-service build && ./util/minify_dist_geojson.js

⠸  Building for production...

 WARNING  Compiled with 3 warnings                                      00:47:13

Module Warning (from ./node_modules/eslint-loader/index.js):
error: 'eventBus' is not defined (no-undef) at src/views/watershed/WatershedHanfordPlumes.vue:83:7:
  81 |   methods: {
  82 |     emit: function (method, args) {
> 83 |       eventBus.$emit(method, args)
     |       ^
  84 |     }
  85 |   }
  86 | }

1 error found.

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
 warning  

asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  js/chunk-vendors.f43c8a4e.js (479 KiB)
  geojson/Cascadia.geojson (1.81 MiB)
  geojson/CascadiaMegaregion.geojson (1.76 MiB)
  geojson/ColumbiaGeneratingStation.jpg (357 KiB)
  geojson/CascadiaSubstations.geojson (1.92 MiB)
  geojson/CascadiaFreeway.geojson (4.47 MiB)
  geojson/HanfordLabels-old.geojson (6.53 MiB)
  geojson/megaregion.geojson (481 KiB)
  geojson/CBP-Crops.geojson (8.84 MiB)
  geojson/OtherMegaregions.geojson (1.4 MiB)
  geojson/HanfordLabels.geojson (8.82 MiB)
  geojson/Highways.geojson (8.24 MiB)
  geojson/NA_Highways.geojson (5.88 MiB)
  geojson/railroads2.geojson (3.54 MiB)
  geojson/railroads.geojson (23.4 MiB)
  geojson/USmegaregions.geojson (1.76 MiB)
  geojson/Urban.geojson (21.8 MiB)
  geojson/USmegaregions2.geojson (1.76 MiB)
  images/BoardmanCoalPlant.jpg (261 KiB)
  images/Cascade2.jpg (349 KiB)
  images/ColumbiaGeneratingStation.jpg (357 KiB)
  images/CascadiaMegaregion-sm.jpg (4.5 MiB)
  images/CascadiaMegaregionFullsize.jpg (5.32 MiB)
  images/Dams/BonnevilleDam.jpg (371 KiB)
  images/Dams/BrilliantDamExpansion.jpg (277 KiB)
  images/Dams/BridgeRiverDam.jpg (553 KiB)
  images/Dams/BridgeRiverPowerhouse.jpg (426 KiB)
  images/Dams/ChiefJosephDam.jpg (391 KiB)
  images/Dams/CulmbackDam.jpg (284 KiB)
  images/Dams/DiabloDam.jpg (348 KiB)
  images/Dams/DworshakDam.jpg (499 KiB)
  images/Dams/HellsCanyonDam.jpg (251 KiB)
  images/Dams/ForrestKerrDam.jpg (410 KiB)
  images/Dams/LowerBakerDam.jpg (254 KiB)
  images/Dams/LibbyDam.jpg (586 KiB)
  images/Dams/NoxonRapidsDam.jpg (546 KiB)
  images/Dams/RoundButteDam.jpg (334 KiB)
  images/Dams/RuskinDam.jpg (428 KiB)
  images/Dams/SelisKsankaQlispe.jpg (461 KiB)
  images/Dams/SwiftDam.jpg (288 KiB)
  images/Fennica.png (345 KiB)
  images/Hanford/F-Reactor.jpg (421 KiB)
  images/Hanford/HanfordEmergency.gif (249 KiB)
  images/Hanford/TunnelCollapse.png (273 KiB)
  images/Legacy/118-D-6.jpg (468 KiB)
  images/Legacy/118-H-6.jpg (481 KiB)
  images/Legacy/618-10.jpg (431 KiB)
  images/Legacy/FastFlux.jpg (308 KiB)
  images/NatGas-probs/BennetMountain.jpg (358 KiB)
  images/GrandCoulee.jpg (2.27 MiB)
  images/NatGas-probs/CoyoteSpringsII.jpg (304 KiB)
  images/NatGas-probs/Encogen.jpg (257 KiB)
  images/NatGas-probs/FerndaleGeneratingStation.jpg (312 KiB)
  images/NatGas-probs/CoyoteSpringsII.png (732 KiB)
  images/NatGas-probs/Goldendale.jpg (265 KiB)
  images/NatGas-probs/HumboldtBay.jpg (514 KiB)
  images/NatGas/CoyoteSpringsII.jpg (288 KiB)
  images/NatGas/BurrardGeneratingStation.jpg (527 KiB)
  images/NatGas/CoyoteSpringsII.png (732 KiB)
  images/NatGas/FerndaleGeneratingStation.jpg (297 KiB)
  images/NatGas/FredericksonLP.jpg (519 KiB)
  images/NatGas/FredericksonIGeneratingStation.jpg (319 KiB)
  images/NatGas/BennetMountain.jpg (1.8 MiB)
  images/NatGas/FredoniaGeneratingStation.jpg (252 KiB)
  images/NatGas/HermistonPowerPartnership.jpg (289 KiB)
  images/NatGas/Goldendale.jpg (462 KiB)
  images/NatGas/IslandGeneration.jpg (326 KiB)
  images/NatGas/HumboldtBay.jpg (478 KiB)
  images/NatGas/RiverRoad.jpg (322 KiB)
  images/NatGas/PortWestward.jpg (401 KiB)
  images/Refineries/CherryPointRefinery.jpg (300 KiB)
  images/NatGas/Encogen.jpg (2.07 MiB)
  images/Refineries/PrinceGeorgeRefinery.jpg (289 KiB)
  images/sealion.png (565 KiB)
  images/TransaltaCentraliaGeneration.jpg (322 KiB)
  images/Wind/JuniperCanyon.jpg (263 KiB)
  images/Wind/TucannonRiverWindFarm.jpg (320 KiB)
  images/Wind/WhiteCreekWindProject.jpg (245 KiB)
  images/Wind/WindyFlats.jpg (409 KiB)

 warning  

entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (538 KiB)
      css/chunk-vendors.d6a48ce3.css
      js/chunk-vendors.f43c8a4e.js
      css/app.2938da12.css
      js/app.5ce902f9.js

  File                                   Size              Gzipped

  dist/js/chunk-vendors.f43c8a4e.js      478.97 kb         136.37 kb
  dist/js/app.5ce902f9.js                44.19 kb          11.21 kb
  dist/js/chunk-86de.9dec2f56.js         10.44 kb          4.49 kb
  dist/js/chunk-7c15.0c1f674b.js         7.71 kb           3.38 kb
  dist/js/chunk-843a.68774110.js         7.22 kb           2.91 kb
  dist/js/8628.ef8b47c8.js               6.90 kb           2.53 kb
  dist/js/chunk-f8a0.7105c8ac.js         6.19 kb           2.84 kb
  dist/js/chunk-0445.6e0e635c.js         5.78 kb           2.64 kb
  dist/js/chunk-26d3.5daa2135.js         4.42 kb           2.00 kb
  dist/js/chunk-d759.ab3053b4.js         4.40 kb           2.25 kb
  dist/js/chunk-3b47.6fd193d8.js         3.73 kb           1.75 kb
  dist/js/chunk-5cea.bbbacbdb.js         3.65 kb           1.74 kb
  dist/js/chunk-6e80.723fc171.js         2.89 kb           1.47 kb
  dist/js/chunk-6076.08788446.js         2.28 kb           0.88 kb
  dist/js/81d0.686ca118.js               0.45 kb           0.30 kb
  dist/js/753a.5e451895.js               0.44 kb           0.30 kb
  dist/css/chunk-vendors.d6a48ce3.css    7.97 kb           2.14 kb
  dist/css/app.2938da12.css              7.10 kb           1.97 kb
  dist/css/chunk-0445.e4e403f5.css       0.62 kb           0.29 kb
  dist/css/chunk-86de.c32ea63b.css       0.53 kb           0.25 kb
  dist/css/chunk-843a.95dd2269.css       0.53 kb           0.25 kb
  dist/css/chunk-f8a0.989c9e87.css       0.53 kb           0.25 kb
  dist/css/chunk-7c15.3c8c893d.css       0.53 kb           0.25 kb
  dist/css/chunk-6076.3e9ab37c.css       0.53 kb           0.25 kb
  dist/css/chunk-3b47.bc86d7e0.css       0.42 kb           0.20 kb
  dist/css/chunk-5cea.eba0f3f1.css       0.38 kb           0.18 kb
  dist/css/chunk-26d3.83302737.css       0.38 kb           0.18 kb
  dist/css/chunk-d759.97936201.css       0.24 kb           0.17 kb
  dist/css/chunk-6e80.4a3ec6fc.css       0.19 kb           0.14 kb

  Images and other types of assets omitted.

 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
                                  
undefined:1
����
^

SyntaxError: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
    at /home/brian/Git/ecotopia-today/util/minify_dist_geojson.js:29:29
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ecotopia-today@0.0.1 build: `vue-cli-service build && ./util/minify_dist_geojson.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ecotopia-today@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/brian/.npm/_logs/2018-09-30T05_47_14_191Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ecotopia-today@0.0.1 predeploy: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ecotopia-today@0.0.1 predeploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/brian/.npm/_logs/2018-09-30T05_47_14_203Z-debug.log

**Comment by edwardsharp** [comment]
@Brian393 by the looks of things (which is really verbose/long) your .geoJSON files are not valid (meaning they are not valid JSON). the minify script might tell you what's wrong (run `node util/minify_dist_geojson.js`) or when you view the .geoJSON files in your text editor (atom) you can run a command to validate that (like https://atom.io/packages/jsonlint)
