### ISSUE TITLE
Bioregion-3 - new commit

### ISSUE THREAD

**Issue by Brian393** [Brian393/ecotopia-today#6]
@edwardsharp

Feel free to have a look at the new commit of Bioregion-3, thanks, Brian

PS- there were also some small details committed to Bioregion-2 and then merged to master, but just text stuff, no problem there.

**Comment by edwardsharp** [comment]
@Brian393 just this commit? https://github.com/Brian393/ecotopia-today/commit/d1b63d253a99d59bbd0a32e9523f571965649fc4#diff-b939125515c54d7e4323ce229da02e31R11

it looks fine. does it compile and work like you want? 

one thing is correctly incrementing the `id` field in your .geoJSON comment here: https://github.com/Brian393/ecotopia-today/commit/d1b63d253a99d59bbd0a32e9523f571965649fc4#r30841014

**Comment by edwardsharp** [comment]
also, FWIW, there seems to be something gnarly going on with the dams/transformation now: https://cascadia.ecotopia.today/#/watershed/dams/transformation

after the animation the dam pictures will start strobing. my guess is that it's related to a hover event causing some kind of weird render loop (possibly changing the opacity?)

**Comment by Brian393** [comment]
@edwardsharp 

Thanks, ed, for pointing out the integer thing. I have not yet tried to correlate the geojson keys and the listeners, I just started looking at that today.

Also, I guess you are busy and thought I would include the question about the strobing in a whole group of other questions. Anyway, if you can figure out how to fix it, would be great. Otherwise I have a work-around in mind but I would prefer a real solution.

I will try compiling later tonight. all the best, Brian
